### ISSUE TITLE
Non-blocking Runs

### ISSUE THREAD

**Issue by onlydole** [electron/sheriff#42]
Howdy, team! It would be wonderful to have the ability to have Sheriff run and "continue on error" if there are folks not added to an Org yet, and continue to enforce the configuration as code that has been set. 

Right now, if there's someone that's pending an org invite, it blocks any other operations from completing.

**Comment by MarshallOfSound** [comment]
This makes sense for the inverse case (where someone leaves the org).  If someone leaves the org it shouldn't block permission runs.

For the case you outlined where they haven't joined yet I'd strongly recommend either running a Sheriff Dry Run on each PR or using something similar to what we use on `electron/.permissions` --> https://github.com/codebytere/governance-check which does a fast-pass of the config file and ensures it's loose validity (including verifying org membership)

**Comment by onlydole** [comment]
Thank you, @MarshallOfSound! That's exactly what I was looking for 😁
