### ISSUE TITLE
GitHub user case sensitivity 

### ISSUE THREAD

**Issue by onlydole** [electron/sheriff#43]
Right now, Sheriff manipulates users in a case-sensitive manner, though it would be nice to have the ability to use all lowercase and defer any lookups to GitHub's API.

**Comment by MarshallOfSound** [comment]
I can't find the reference right now, but it's my understanding that GitHub explicitly says something like "you should use user ids, but if you really want to use usernames please at least make the checks case sensitive".  That might be old advise, but it's what I went off with this when it was built 😅

**Comment by onlydole** [comment]
Ah! Got it - thank you, @MarshallOfSound. I'll take a look to see if there's any way I can catch that in the PR step or otherwise. I appreciate all your help!
